#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  2 10:55:13 2020

@author: pallavideshmukh
"""

import datetime
import time

print ("BOSCH Dishwasher")
print("You can set 6 machines in one go")

count=0
while count <=6 :

    print ("Please select the mode")

    mode=input("A Intensive Kadhai, B Express Sparkle, C Auto, D Eco, E Quick, F Prerinse ").lower()

    if mode=="a":
        print ("30 sec")
        start=datetime.datetime.now()
        print ("The time now  is" + str(start))
        print("The machine is running wait for 30 seconds")
        time.sleep(30)
        print("Your machine is over")
        end=datetime.datetime.now()
        print("The time now in seconds is" + str(end))
        count=count+1
        more=input("Do you want to set one more machine? ans in y or n ")
      
        if more== "y" :
            print("Please Continue")
        
        else :
            break
            
    
    elif mode=="b":
        print ("15 sec")
        start=datetime.datetime.now()
        print ("The time now  is" + str(start))
        print("The machine is running wait for 15 seconds")
        time.sleep(15)
        print("Your machine is over")
        end=datetime.datetime.now()
        print("The time now in seconds is" + str(end))  
        count=count+1
        more=input("Do you want to set one more machine? ans in y or n ")
        
        if more== "y" :
            print("Please Continue")
            
        else :
            break
    
    elif mode=="c":
        print ("20 sec")
        start=datetime.datetime.now()
        print ("The time now  is" + str(start))
        print("The machine is running wait for 20 seconds")
        time.sleep(20)
        print("Your machine is over")
        end=datetime.datetime.now()
        print("The time now in seconds is" + str(end)) 
        count=count+1
        more=input("Do you want to set one more machine? ans in y or n ").lower()
        
        if more== "y" :
            print("Please Continue")
           
        elif more=="n" :
            break

    elif mode=="d":
        print ("25 sec")
        start=datetime.datetime.now()
        print ("The time now  is" + str(start))
        print("The machine is running wait for 25 seconds")
        time.sleep(25)
        print("Your machine is over")
        end=datetime.datetime.now()
        print("The time now in seconds is" + str(end)) 
        count=count+1
        more=input("Do you want to set one more machine? ans in y or n ")
        
        if more== "y":
            print("Please Continue")
        else :
            break
        
    elif mode=="e":
        print ("10 sec")
        start=datetime.datetime.now()
        print ("The time now  is" + str(start))
        print("The machine is running wait for 10 seconds")
        time.sleep(10)
        print("Your machine is over")
        end=datetime.datetime.now()
        print("The time now in seconds is" + str(end)) 
        count=count+1
        more=input("Do you want to set one more machine? ans in y or n ")
       
        if more== "y" :
            print("Please Continue")
           
        else :
            break
        
    elif mode=="f":
        print ("5 sec")
        start=datetime.datetime.now()
        print ("The time now  is" + str(start))
        print("The machine is running wait for 5 seconds")
        time.sleep(5)
        print("Your machine is over")
        end=datetime.datetime.now()
        print("The time now in seconds is" + str(end)) 
        count=count+1
        more=input("Do you want to set one more machine? ans in y or n ")
        
        if more== "y":
           print("Please Continue")
        else:
            break
    else :
        print("Sorry Such a mode does not exist ")
        count=count+0
        
    if count>=6 :
        print("Your detergent is over !")
        break
print("Thank you for using Bosch Dishwasher")
print("Hope your dishes are sparkling!!")